# **Numpy Practice Questions**



1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
A = np.array([6,7,99])
B = np.array([4, 5, 6])

In [ ]:
 np.vstack((A, B))

array([[ 6,  7, 99],
       [ 4,  5,  6]])

In [ ]:
np.hstack((A,B))

array([ 6,  7, 99,  4,  5,  6])

2. Find common elements between A and B.

In [ ]:
np.intersect1d(A, B)

array([6])

3. Extract all numbers from A which are within a specific range. eg between 5 and 10.


In [ ]:
 A[(A >= 5) & (A <= 10)]

array([6, 7])

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

In [ ]:
Filtered= iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

In [ ]:
Filtered

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## **Practice Questions for Pandas**


1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
df["Min.Price"]

0     12.9
1     29.2
2     25.9
3      NaN
4      NaN
      ... 
88    16.6
89    17.6
90    22.9
91    21.8
92    24.8
Name: Min.Price, Length: 93, dtype: float64

In [ ]:
df["Max.Price"]

0     18.8
1     38.7
2     32.3
3     44.6
4      NaN
      ... 
88    22.7
89    22.4
90    23.7
91    23.5
92    28.5
Name: Max.Price, Length: 93, dtype: float64

In [ ]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

In [ ]:
df["Min.Price"]

0     12.900000
1     29.200000
2     25.900000
3     17.118605
4     17.118605
        ...    
88    16.600000
89    17.600000
90    22.900000
91    21.800000
92    24.800000
Name: Min.Price, Length: 93, dtype: float64

In [ ]:
df["Max.Price"]

0     18.800000
1     38.700000
2     32.300000
3     44.600000
4     21.459091
        ...    
88    22.700000
89    22.400000
90    23.700000
91    23.500000
92    28.500000
Name: Max.Price, Length: 93, dtype: float64

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [ ]:
sum=df.sum(axis=1)

In [ ]:
df[sum>100]

0   1   2   3
1   32  35  36  33
2   34  36  11  25
3   25  36  14  30
4   28  10  34  38
7   35  37  26  16
11  28  17  26  33
13  29  37  31  23
14  36  15  27  34